version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
      - frontend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: jesus
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_wHoEYl8X4pQx
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db

  api1:
    build: ./api1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jesus
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_wHoEYl8X4pQx
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  api2:
    build: ./api2
    environment:
      MONGODB_URL: mongodb://mongo:27017
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  postgres_data:
  mongo_data: