# api1/Dockerfile
FROM maven:3.8.6-eclipse-temurin-17 AS build
WORKDIR /app
# Copia apenas os arquivos de api1
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]